GoldSova/GoldSova/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import MyLoginView, MyLogoutView
from users import views as UsersViews



urlpatterns = [
    path('admin_work_with_site/', admin.site.urls, name = 'admin_action'),
    path('',include('main.urls')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('reg/', include('users.urls')),
    path('order/', include('order.urls')),
    path('login/', MyLoginView.as_view(template_name='users/user.html',redirect_authenticated_user=True), name='auth'),
    path('profile/', UsersViews.profile, name='profile'),
    path('edit/', UsersViews.edit, name='edit'),
    path('logout/',MyLogoutView.logout_site, name='exit'),
] 

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GoldSova/catalog/urls.py
from . import views
from django.urls import path

app_name = 'catalog'

urlpatterns = [
   path('', views.product_list, name='product_list'),
   path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
   path('<int:id>/<slug:slug>', views.product_detail, name='product_detail')
]

GoldSova/main/urls.py
from . import views
from django.urls import path

urlpatterns = [
   path('',views.index, name='home'),
]

GoldSova/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
   path('', views.order_conditions, name='order'),
   path('make_order',views.make_order, name='make_order_form'),
   path('download', views.download_file, name='download_file'),
   path('delete_order/<int:number_order>', views.delete_order, name='delete_order')
]

GoldSova/main/models.py
from django.db import models

# Create your models here.

GoldSova/main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html', {'title': 'Главная страница'})

GoldSova/main/templates/main/index.html
{% extends 'main/main.html' %}

{% block button_section %}
{% if user.is_authenticated %}
<div class="navbar-nav">
    <a href="{% url 'exit' %}" class="btn btn-outline-danger mr-2">Выход</a>
</div>
{% else %}
    <div class="navbar-nav">
        <a href="{% url 'reg' %}" class="btn btn-outline-danger mr-2">Регистрация</a>
    </div>
{% endif %}
{% endblock button_section %}

{% block main_section %}
{% if user.is_authenticated %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-6 fw-normal">Сделать заказ?</h1>
        <p class="lead fw-normal">Перейдите в "Заказать товар"</p>
        <a class="btn btn-outline-danger mr-2" href="">Сделать заказ</a>
            <p><br></p>
            <h1 class="lead fw-normal">Не определились с выбором?</h1>
            <a class="btn btn-outline-danger mr-2" href="{% url 'catalog:product_list' %}">Каталог</a>
        </div>
    </div>
{% else %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-6 fw-normal">Сделать заказ?</h1>
        <p class="lead fw-normal">Для того, чтобы сделать заказ, вам нужно авторизироватся</p>
        <a class="btn btn-outline-danger mr-2" href="{% url 'auth' %}">Авторизация</a>
            <p><br></p>
            <h1 class="lead fw-normal">Нет в нашей базе?</h1>
            <a class="btn btn-outline-danger mr-2" href="{% url 'reg' %}">Регистрация</a>
        </div>
    </div>
{% endif %}
{% endblock main_section %}


{% block other_section %}
    <div class ="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
        {% filter upper %}
            <p class="lead fw-normal">Сайт в разработке</p>
        {% endfilter %}
        <form action="https://zolotayasova.com/" target="_blank">
            <button class="btn btn-warning">На офицальный сайт</button>
        </form>
    </div>
{% endblock other_section %}

GoldSova/main/templates/main/main.html
{% load static %}
<!DOCTYPE html>

<html lang="ru-RU">
    <head>
      <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="icon" type="image/png" href="{% static 'main/img/logo.png' %}">
        <title>{{ title }}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" aria-label="Thirteenth navbar example">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
              <a href="https://zolotayasova.com/"><img src="{% static 'main/img/logo.png' %}" width="30%" height="30%" ></a>
              <p class="navbar-brand col-lg-3 me-0">Золотая Сова</p>
              <ul class="navbar-nav col-lg-5 justify-content-lg-center">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Главная</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'order:order' %}">Заказ товара</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link active" href="{% url 'catalog:product_list' %}">Каталог</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'profile' %}">Личный кабинет</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Главная</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="https://zolotayasova.com/">Основной сайт</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link active" href="{% url 'catalog:product_list' %}">Каталог</a>
                  </li>
                {% endif %}

              </ul>
            </div>
            <hr>
            {% block button_section %}
            {% endblock button_section %}
            {% if user.is_authenticated and user.is_staff %}
            <div class="navbar-nav">
              <p>&nbsp;&nbsp;&nbsp;</p>
              <a href="/admin_work_with_site/" class="btn btn-outline-info">Администрирование</a>
            </div>
            {% endif %}
          </div>
         </nav>
        <main>
            <br><br>
            <div class="container col-md-8">
                {% if messages %}
                    {% for mess in messages %}
                    <div class="opacity-75 p-2 m-1 bg-primary text-light fw-bold rounded">{{ mess }}</div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="container" >
                {% block main_section  %}

                {% endblock main_section %}
            </div>
            <div class="container" >
                {% block other_section  %}

                {% endblock other_section %}

            <div class="container" >
              {% block new3_section  %}

              {% endblock new3_section  %}
          </div>

        </main>
    </body>
</html>