GoldSova/GoldSova/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import MyLoginView, MyLogoutView
from users import views as UsersViews



urlpatterns = [
    path('admin_work_with_site/', admin.site.urls, name = 'admin_action'),
    path('',include('main.urls')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('reg/', include('users.urls')),
    path('order/', include('order.urls')),
    path('login/', MyLoginView.as_view(template_name='users/user.html',redirect_authenticated_user=True), name='auth'),
    path('profile/', UsersViews.profile, name='profile'),
    path('edit/', UsersViews.edit, name='edit'),
    path('logout/',MyLogoutView.logout_site, name='exit'),
] 

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GoldSova/main/urls.py
from . import views
from django.urls import path

urlpatterns = [
   path('',views.index, name='home'),
]

GoldSova/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
   path('', views.order_conditions, name='order'),
   path('make_order',views.make_order, name='make_order_form'),
   path('download', views.download_file, name='download_file'),
   path('delete_order/<int:number_order>', views.delete_order, name='delete_order')
]

GoldSova/users/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as authViews

from .views import EmailVerify


urlpatterns = [
   path('',views.register, name='reg'),
   path('confirm_email/', TemplateView.as_view(template_name = 'users/confirm_email.html'), name='confirm_email'),
   path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
   path('respassword/',authViews.PasswordResetView.as_view(template_name='users/pass_reset.html'), name='pass_reset'),
   path('password_reset_confirm/<uidb64>/<token>/',
         authViews.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
         name='password_reset_confirm'),
   path('password_reset/done/',
         authViews.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
         name='password_reset_done'),
   path('password_reset_complete/',
         authViews.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
         name='password_reset_complete'),
]

GoldSova/users/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _
from PIL import Image

from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


class CustomUserManager(BaseUserManager):

    def create_user(self, email, password, **extra_fields):

        if not email:
            raise ValueError(_('Почта должна быть'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('email_verify', True)
        extra_fields.setdefault('succes_user', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)



class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    succes_user = models.BooleanField('Потверждение пользователя', default=False,)
    email_verify = models.BooleanField('Потверждение почты', default=False,)
    phone = PhoneNumberField(region='RU')
    adress = models.CharField('Адресс', default='',max_length=250)
    org = models.TextField('Организация', default='',max_length=100)

    objects = CustomUserManager()
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    img = models.ImageField(default='dafault.jpg', upload_to='user_images')
   
    def __str__(self):
        return f'Пользователь: {self.user.email}'
    

    class Meta:
        verbose_name = 'Информация о пользователе'
        verbose_name_plural = 'Информация о пользователе'

    def save(self, *args, **kwargs):
        super(Profile,self).save(*args, **kwargs)

        image = Image.open(self.img.path)

        if image.height > 256 or image.width > 256:
            resize = (256, 256)
            image.thumbnail(resize)
            image.save(self.img.path)

@receiver(pre_delete, sender=Profile)
def mymodel_delete(sender, instance, **kwargs):
    instance.img.delete(False)

GoldSova/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model, authenticate
from django.utils.translation import gettext_lazy as _

from .models import Profile
from phonenumber_field.formfields import PhoneNumberField
from django.core.exceptions import ValidationError
from .utils import send_email_verify

User = get_user_model()

class MyAuthenticationForm(AuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(
                self.request,
                username=username,
                password=password,
            )
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)
            if  not self.user_cache.email_verify:
                send_email_verify(self.request, self.user_cache)
                raise ValidationError(
                    'Ваша почта не потверждена. Письмо отправлено',
                    code='invalid_login',
                )
        return self.cleaned_data

class UserCreateOurReg(UserCreationForm):

    email = forms.EmailField(required=True, label=('Ваша почта'))
    phone = PhoneNumberField(region='RU', widget=forms.TextInput(attrs={'placeholder': _('+7(999)123-45-67')}), label=_("Номер телфона"), required=False)

    class Meta:
        model = User
        fields = ['email','phone', 'password1', 'password2']

class UserEditUpdateForm(forms.ModelForm):
    phone = PhoneNumberField(region='RU', widget=forms.TextInput(attrs={'placeholder': _('+7(999)123-45-67')}), label=_("Номер телфона"), required=False)
    adress = forms.CharField(label=('Ваш адресс'))
    org = forms.CharField(label=('Ваша организация'), max_length=100)
    
    class Meta:
        model = User
        fields = ['first_name','last_name','phone','adress','org']

class ImgUserEditUpdateForm(forms.ModelForm):
    img = forms.ImageField(label=('Фотография профиля'))

    class Meta:
        model = Profile
        fields = ['img' ]

GoldSova/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, get_user_model, login, logout

from django.views import View
from django.utils.http import urlsafe_base64_decode
from django.core.exceptions import ValidationError
from django.contrib.auth.tokens import default_token_generator as token_generator


from .forms import MyAuthenticationForm, UserCreateOurReg, ImgUserEditUpdateForm, UserEditUpdateForm
from order.models import MakeOrder
from .utils import send_email_verify, login_excluded

User = get_user_model()


class MyLoginView(LoginView):
    form_class = MyAuthenticationForm
    
class MyLogoutView(LogoutView):
    def logout_site(request):
        logout(request)
        return redirect('auth')


class EmailVerify(View):

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)
        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            email = request.user.email
            messages.success(request, f'Успешная потверждение почты: {email}')
            return redirect('profile')
        messages.warning(request, f'Ошибка в потверждении почты')
        return redirect('home')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


@login_required
def profile(request):
    history = MakeOrder.objects.filter(email_id = request.user.id)
    return render(request, 'users/profile.html', 
                  {
                    'title': 'Профиль',
                    'history': history,
                  })

@login_required
def edit(request):
    try:
        if request.method == "POST":
            img_profile = ImgUserEditUpdateForm(request.POST, request.FILES, instance=request.user.profile)
            update_user = UserEditUpdateForm(request.POST, instance=request.user)
            if update_user.is_valid() and img_profile.is_valid():
                update_user.save()
                img_profile.save()
                email = update_user.cleaned_data.get('email')
                messages.success(request, f'Успешная обновление данных пользователя {email}')
                return redirect('profile')
        else:
            img_profile = ImgUserEditUpdateForm(instance=request.user.profile)
            update_user = UserEditUpdateForm(instance=request.user)
            data ={
            'img_profile': img_profile,
            'update_user': update_user,
            'title': 'Обновление профиля'
            }
        return render(request, 'users/edit.html', data)
    except Exception:
        messages.warning('profile')
        return redirect('profile')

@login_excluded('profile')
def register(request):
    if request.method == "POST":
        form = UserCreateOurReg(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_email_verify(request, user)
            messages.success(request, f'Сообщение для потверждение было отправлено вам на: {email}')
            return redirect('confirm_email')
    else:
        form = UserCreateOurReg()

    return render(request, 'users/registration.html', {'form': form, 'title': 'Регистрация'})

GoldSova/users/templates/users/confirm_email.html
{% extends 'users/login.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block main_section  %}
    <div class="wrap-login100">
        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}
        <span class="login100-form-title p-b-26">
            Добро пожаловать
            <br>
        </span>
        <span class="login100-form-title p-b-48">
            <img src="{% static 'main/img/logo.png' %}" width="30%" height="30%" >
        </span>
        
        <form class="login100-form validate-form" method="POST">
            <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn"></div>
                    <a class="login100-form-btn" href="{% url 'auth' %}"> Вернуться назад</a>
                </div>
        </div>
        </form>
    </form>
</div>      
{% endblock main_section %}

{% block push_massage  %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
    <p class="lead fw-normal">Для верификации вашего аккаунта, потвердите вашу почту!</p>
</div>
{% endblock push_massage %}

GoldSova/users/templates/users/edit.html
{% extends 'main/main.html' %}
{% load crispy_forms_tags %}

{% block button_section %}
<div class="navbar-nav">
    <a href="{% url 'exit' %}" class="btn btn-outline-danger mr-2">Выход</a>
</div>
{% endblock button_section %}


{% block main_section  %}
  <div class="d-flex text-body-secondary pt-3">
    <img class="mr-2 rounded" style="width: 64px; height: 64px;" src="{{ user.profile.img.url }}">
    <p class="pb-3 mb-0 small lh-sm border-bottom",style="white-space: pre-wrap;">
      <strong class="d-block text-gray-dark">&nbsp;&nbsp;&nbsp;&nbsp;ID пользователя: {{ user.id }}</strong>
      <strong class="d-block text-blue-dark">&nbsp;&nbsp;&nbsp;&nbsp;Имя и фамилия: {{ user.first_name }}&nbsp;{{ user.last_name }}</strong>
      {% if user.org == '' %}
      <strong class="d-block text-blue-dark">&nbsp;&nbsp;&nbsp;&nbsp;Организация: Отсутсвует</strong>
      {% else %}
      <strong class="d-block text-blue-dark">&nbsp;&nbsp;&nbsp;&nbsp;Организация: {{ user.org }}</strong>
      {% endif %}
    </p>
  </div>
{% endblock main_section %}

{% block other_section %}
<hr> 
<div class="form-registe col-md-6 mx-auto my-2">
  <br>
  <h4 class="text-center">Изменить информацию о пользователе</h4>
          <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ update_user|crispy }}
              <hr>
              {{ img_profile|crispy }}
              <p><br></p>
              <button type="sumbit" class="btn btn-outline-primary">Обновить</button>
          </form>
</div>

{% endblock other_section %}

{% block new3_section  %}

{% endblock new3_section  %}

GoldSova/users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'main/img/logo.png' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'users/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'users/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'users/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
    <div class="limiter">
		<div class="container-login100">
			
			{% block main_section  %}
			{% csrf_token %}
			{% endblock main_section  %}
			{% block other  %}
			{% csrf_token %}
    		{% endblock other   %}
			{% block push_massage  %}
			{% csrf_token %}
			{% endblock push_massage %}
		</div>
	</div>


	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'users/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'users/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'users/js/main.js' %}"></script>

</body>
</html>

GoldSova/users/templates/users/pass_reset.html
{% extends 'users/login.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block main_section  %}
<div class="wrap-login100">
    <span class="login100-form-title p-b-26">
        Восстановление пароля
        <br>
    </span>
    <span class="login100-form-title p-b-48">
        <img src="{% static 'main/img/logo.png' %}" width="30%" height="30%" >
    </span>
    <form class="login100-form validate-form" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <p><br></p>
                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn">
                            отправить
                        </button>
                    </div>
                </div>
            </form>
        </div>
{% endblock main_section %}

GoldSova/users/templates/users/password_reset_complete.html
{% extends 'users/login.html' %}

{% load static %}
{% load crispy_forms_tags %}



{% block main_section  %}
    <div class="wrap-login100">
        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}
        <span class="login100-form-title p-b-26">
            Добро пожаловать
            <br>
        </span>
        <span class="login100-form-title p-b-48">
            <img src="{% static 'main/img/logo.png' %}" width="30%" height="30%" >
        </span>
        
        <form class="login100-form validate-form" method="POST">
            <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn"></div>
                    <a class="login100-form-btn" href="{% url 'auth' %}"> Вернуться назад</a>
                </div>
        </div>
        </form>
        </form>
</div>      
{% endblock main_section %}

{% block push_massage  %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
    <div class="opacity-75 p-2 m-1 bg-primary text-light fw-bold rounded">Успешная смена пороля</div>
</div>
{% endblock push_massage %}

GoldSova/users/templates/users/password_reset_confirm.html
{% extends 'users/login.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block main_section  %}
<div class="wrap-login100">
    <span class="login100-form-title p-b-26">
        Установка нового пароля
        <br>
    </span>
    <span class="login100-form-title p-b-48">
        <img src="{% static 'main/img/logo.png' %}" width="30%" height="30%" >
    </span>
    <form class="login100-form validate-form" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <p><br></p>
                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn">
                            Поменять пароль
                        </button>
                    </div>
                </div>
            </form>
        </div>
{% endblock main_section %}

GoldSova/users/templates/users/password_reset_done.html
{% extends 'users/login.html' %}

{% load static %}
{% load crispy_forms_tags %}



{% block main_section  %}
    <div class="wrap-login100">
        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}
        <span class="login100-form-title p-b-26">
            Добро пожаловать
            <br>
        </span>
        <span class="login100-form-title p-b-48">
            <img src="{% static 'main/img/logo.png' %}" width="30%" height="30%" >
        </span>
        
        <form class="login100-form validate-form" method="POST">
            <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn"></div>
                    <a class="login100-form-btn" href="{% url 'auth' %}"> Вернуться назад</a>
                </div>
        </div>
        </form>
    </form>
</div>      
{% endblock main_section %}

{% block push_massage  %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
    <div class="opacity-75 p-2 m-1 bg-primary text-light fw-bold rounded">Сообщение было отправлено вам на почту</div>
</div>
{% endblock push_massage %}

GoldSova/users/templates/users/profile.html
{% extends 'main/main.html' %}
{% load crispy_forms_tags %}

{% block button_section %}
<div class="navbar-nav">
    <a href="{% url 'exit' %}" class="btn btn-outline-danger mr-2">Выход</a>
</div>
{% endblock button_section %}


{% block main_section  %}
  <div class="d-flex text-body-secondary pt-3">
    <img class="mr-2 rounded" style="width: 64px; height: 64px;" src="{{ user.profile.img.url }}">
    <p class="pb-3 mb-0 small lh-sm border-bottom",style="white-space: pre-wrap;">
      <strong class="d-block text-gray-dark">&nbsp;&nbsp;&nbsp;&nbsp;ID пользователя: {{ user.id }}</strong>
      <strong class="d-block text-blue-dark">&nbsp;&nbsp;&nbsp;&nbsp;Имя и фамилия: {{ user.first_name }}&nbsp;{{ user.last_name }}</strong>
      {% if user.org == '' %}
      <strong class="d-block text-blue-dark">&nbsp;&nbsp;&nbsp;&nbsp;Организация: Отсутсвует</strong>
      {% else %}
      <strong class="d-block text-blue-dark">&nbsp;&nbsp;&nbsp;&nbsp;Организация: {{ user.org }}</strong>
      {% endif %}
    </p>
    
  </div>
{% endblock main_section %}

{% block other_section %}
  {% if user.succes_user == False %}
    <strong class="d-block text-blue-dark" >&nbsp;&nbsp;&nbsp;&nbsp;Потвержденный пользователь: <p class="spinner-grow text-danger" role="status">&nbsp;</p></strong>
  {% else %}
    <strong class="d-block text-blue-dark" >&nbsp;&nbsp;&nbsp;&nbsp;Потвержденный пользователь: <p class="spinner-grow text-success" role="status">&nbsp;</p></strong>
  {% endif %}

{% endblock other_section %}

{% block new3_section  %}
<div class="row gy-3 gy-xxl-5">
  <div class="col">
    <h3 class="text-center">Информация о пользователе</h3>
     <div class="p-3 border bg-light">
          <p>Email:</b> {{ user.email}}</p><hr>
          {% if user.org != '' %}
          <p>Телефон:</b> {{ user.phone}} </p><hr>
          <p>Адрес:</b> {{ user.adress}}</p><hr>
          <p>Организация:</b> {{ user.org }}</p><hr>
          {% else %}
          <p>Телефон:</b> Отсутсвует</p><hr>
          <p>Адрес:</b> Отсутсвует</p><hr>
          <p>Организация:</b> Не указана</p><hr>
          <p>Дата регистрации:</b> {{ user.date_joined }}</p><hr>
          {% endif %}
          {% if user.succes_user == False %}
          <br>
          <hr><p> Для потвержденния пользователя, с вами свяжется оператор</b></p><hr>
          {% endif %}
     </div>
  </div>
  {% if user.succes_user %}
  <div class="col">
    <h3 class="text-center">Заказы</h3>
     <div class="p-3 border ">
      <div class="form-history">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Номер заказа</th>
              <th scope="col">Статус заказа</th>
              <th scope="col">Создание заказа</th>
            </tr>
          </thead>
          {% for el in history %}
          <tbody>
            {% if el.status_order == 1  %}
            <tr class="table-secondary">
              <th scope="row">№ {{ el.number_order }}</th>
              <td>Рассмотрение</td>
              <td>{{ el.created }}&nbsp&nbsp&nbsp<a href="{% url 'order:delete_order' number_order=el.number_order %}" class="btn btn-danger mr-2">Удалить</a></td>
            </tr>
            {% endif %}
            {% if el.status_order == 5  %}
            <tr class="table-success">
              <th scope="row">№ {{ el.number_order }}</th>
              <td>Выполнен</td>
              <td>{{ el.created }}</td>
              
            </tr>
            {% endif %}
            {% if el.status_order == 6 %}
            <tr class="table-danger">
              <th scope="row">№ {{ el.number_order }}</th>
              <td>Отменен</td>
              <td>{{ el.created }}</td>
            </tr>
            {% endif %}
            {% if el.status_order == 2 or el.status_order == 3 or el.status_order == 4  %}
            <tr class="table-warning">
              <th scope="row">№ {{ el.number_order }}</th>
              {% if el.status_order == 2 %}
              <td>Начат</td>
              {% endif %}
              {% if el.status_order == 3 %}
              <td>Потвержден</td>
              {% endif %}
              {% if el.status_order == 4 %}
              <td>Выполнение</td>
              {% endif %}
              <td>{{ el.created }}</td>
            </tr>
            {% endif %}
          </tbody>
          {% endfor %}
        </table>
      </div>
      <p class=""> </p>
     </div>
  </div>
  {% endif %}
    <p class="lead fw-normal text-center">Для того, чтобы обновить/изменить данные профиля 
      <br>
      <small class="text-center"><a class="btn btn-outline-danger" href="{% url 'edit' %}">Обновление</a></small>
    </p>
    
</div>


{% endblock new3_section  %}

GoldSova/users/templates/users/registration.html
{% extends 'users/login.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block other %}
<div class="form-registe col-md-5 p-lg-5 mx-auto my-2">
    <span class="login100-form-title p-b-26">
        Регистрация
        <br>
    </span>
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <p><br></p>
                <div class="container-login100-form-btn">
                    <div class="wrap-login100-form-btn">
                        <div class="login100-form-bgbtn"></div>
                        <button class="login100-form-btn">
                            Регистрация
                        </button>
                    </div>
                </div>
            </form>
            <hr> 
            Уже зарегестрированы? <a href="{% url 'auth' %}">Войти в личный кабинет</a>
</div>
{% endblock other  %}

GoldSova/users/templates/users/user.html
{% extends 'users/login.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block main_section  %}
    <div class="wrap-login100">
        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}
        <span class="login100-form-title p-b-26">
            Добро пожаловать
            <br>
        </span>
        <span class="login100-form-title p-b-48">
            <img src="{% static 'main/img/logo.png' %}" width="30%" height="30%" >
        </span>
        
        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <p><br></p>
            <div class="container-login100-form-btn">
            <div class="wrap-login100-form-btn">
                <div class="login100-form-bgbtn"></div>
                <button class="login100-form-btn">
                    Авторизация
                </button>
            </div>
        </div>
        </form>
        <hr>
        <div class="text-center p-t-115">
            <span class="txt1">
                Нет аккаунта?
            </span>
            <a class="txt2" href="{% url 'reg' %}">
                Зарегестрироваться
            </a>
            <br>
            <span class="txt1">
                Забыли пароль?
            </span>
            <a class="txt2" href="{% url 'pass_reset' %}">
                Восстановление
            </a>
        </div>
    </form>
</div>
        
{% endblock main_section %}

GoldSova/users/templates/users/verify_email.html
{% load i18n %}{% autoescape off %}

Вы получили это письмо, потому что вы (или кто-то другой) пытаетесь зарегестрироваться на сайте {{ domain }}, которая связана с этим адресом электронной почты.

Здраствуйте, дорогой пользователь: {{ user.get_username }},
Потвердите вашу почту, перейдя по ссылке снизу, для того, чтобы закончить регистрацию:

http://{{ domain }}{% url 'verify_email' uidb64=uid token=token %}



{% endautoescape %}