GoldSova/GoldSova/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import MyLoginView, MyLogoutView
from users import views as UsersViews



urlpatterns = [
    path('admin_work_with_site/', admin.site.urls, name = 'admin_action'),
    path('',include('main.urls')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('reg/', include('users.urls')),
    path('order/', include('order.urls')),
    path('login/', MyLoginView.as_view(template_name='users/user.html',redirect_authenticated_user=True), name='auth'),
    path('profile/', UsersViews.profile, name='profile'),
    path('edit/', UsersViews.edit, name='edit'),
    path('logout/',MyLogoutView.logout_site, name='exit'),
] 

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GoldSova/main/urls.py
from . import views
from django.urls import path

urlpatterns = [
   path('',views.index, name='home'),
]

GoldSova/order/urls.py
from . import views
from django.urls import path

app_name = 'order'

urlpatterns = [
   path('', views.order_conditions, name='order'),
   path('make_order',views.make_order, name='make_order_form'),
   path('download', views.download_file, name='download_file'),
   path('delete_order/<int:number_order>', views.delete_order, name='delete_order')
]

GoldSova/order/models.py
from django.db import models
from users.models import User
from .utils import user_directory_path 
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


class MakeOrder(models.Model):

    STATUS = [
        (1, 'Рассмотрение'),
        (2, 'Начато'),
        (3, 'Потвержден'),
        (4, 'Выполнение'),
        (5, 'Выполнен')
    ]

    number_order = models.AutoField('Номер заказа', primary_key = True)
    email = models.ForeignKey(User, on_delete= models.CASCADE)
    file_order = models.FileField('Накладная', upload_to=user_directory_path)
    status_order = models.PositiveSmallIntegerField('Статус заказа', default = 1, choices = STATUS)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    uploaded = models.DateTimeField('Дата обновления', auto_now=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f"Заказ: №{self.number_order}"
    

@receiver(pre_delete, sender=MakeOrder)
def mymodel_delete(sender, instance, **kwargs):
    instance.file_order.delete(False)

GoldSova/order/forms.py
from django import forms
from .models import MakeOrder


class MakeOrderForm(forms.ModelForm):
    file_order = forms.FileField(label=('Загрузить заказ'))

    class Meta:
        model = MakeOrder
        fields = ['file_order',]

class DeleteOrderForm(forms.ModelForm):
    number_order = forms.IntegerField(label=('Введите номер заказа:'))

    class Meta:
        model = MakeOrder
        fields = ['number_order',]

GoldSova/order/views.py
import os
import mimetypes

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required

from .forms import MakeOrderForm, DeleteOrderForm
from .utils import work_with_excel
from .models import MakeOrder


@login_required
def download_file(request):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    filename = 'Заявка.xlsx'
    filepath = BASE_DIR + '/files/' + filename
    work_with_excel(filepath, request.user.adress)
    path = open(filepath, 'rb')
    mime_type, _ = mimetypes.guess_type(filepath)
    response = HttpResponse(path, content_type=mime_type)
    response['Content-Disposition'] = 'attachment; filename=Zayvka.xlsx'
    return response

@login_required
def make_order(request):
    if request.user.succes_user:
        if request.method == "POST":
            ordermake = MakeOrderForm(request.POST, request.FILES)
            org = request.user.org
            adress = request.user.adress
            if ordermake.is_valid():
                instance = ordermake.save(commit=False)
                instance.email_id = request.user.id
                instance.save()
                email = request.user.org
                messages.success(request, f'Заявка {email} отправлена ')
                return redirect('profile')
        else:
            ordermake = MakeOrderForm()
            org = request.user.org
            adress = request.user.adress
        return render(request, 'order/make_order.html', 
                      {
                        'org': org,
                        'adress': adress,
                        'form': ordermake,
                        'title':'Форма отправки заявки'
                      })
    else:
        messages.warning(request, f'У вас не достаточно прав')
        return redirect('profile')

@login_required
def order_conditions(request):
    if request.user.succes_user:
        return render(request, 'order/order.html', 
                      {
                        'title':'Условия оформления заявки'
                      })
    else:
        messages.warning(request, f'У вас не достаточно прав')
        return redirect('profile')


@login_required   
def delete_order(request, number_order):
    order = MakeOrder.objects.get(number_order=number_order)
    if request.user.id == order.email_id:
        messages.success(request, f'Ваш заказ №{order.number_order} удален')
        order.delete()
        return redirect('profile')
    else:
        messages.success(request, f'Не ваш заказ')
        return redirect('profile')
    
    

GoldSova/order/templates/order/make_order.html
{% extends 'main/main.html' %}
{% load crispy_forms_tags %}

{% block button_section %}
    <a href="{% url 'exit' %}" class="btn btn-outline-danger mr-2">Выход</a>
{% endblock button_section %}

{% block main_section %}
<div class="form-registe col-md-5 p-lg-5 mx-auto my-2">
    <h2 class="display-6 fw-normal">Оформление заявки</h2>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <br>
                <hr>
                <p>Ваша организация: <span class="mark">{{ org }}</span></p>
                <hr>
                <p>Ваш адресс: <span class="mark">{{ adress }}</span></p>
                <hr>
                <br>
                {{ form | crispy }}
                <p><br></p>
                <button type="sumbit" class="btn btn-outline-primary">Сделать заказ</button>
            </form>
            <hr>
            
</div>
{% endblock main_section %}

GoldSova/order/templates/order/order.html
{% extends 'main/main.html' %}
{% load crispy_forms_tags %}

{% block button_section %}
    <a href="{% url 'exit' %}" class="btn btn-outline-danger mr-2">Выход</a>
{% endblock button_section %}

{% block main_section %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-body-tertiary">
    <h1 class="display-6 fw-normal">Как происходит заказ</h1>
    <p class="lead fw-normal">По кнопке "Заявка", вы можете получить Excel файл, в котором вам нужно заполнить позиции тех товаров, которые хотите заказать.</p>
    <a href="{% url 'order:download_file' %}" class="btn btn-info">Заявка</a>
    <a href="{% url 'order:make_order_form' %}" class="btn btn-info">Форма отправки заявки</a>
    <p><br></p>
    <h2>Условия заказа продукции</h2>
    <br>
     <figure>
        <blockquote class="blockquote">
           <p>В одной упаковке: <span class="mark">12 бутылок (6 л.)</span>. Минимальный оптовый заказ: <span class="mark">10 упаковок</span></p>
        </blockquote>
        <figcaption class="blockquote-footer">Обьем 0.5</figcaption>
     </figure>
     <figure>
        <blockquote class="blockquote">
           <p>В одной упаковке: <span class="mark">6 бутылок (6 л.)</span>. Минимальный оптовый заказ: <span class="mark">5 упаковок</span></p>
        </blockquote>
        <figcaption class="blockquote-footer">Обьем 1.0</figcaption>
     </figure>
     <figure>
        <blockquote class="blockquote">
           <p>В одной упаковке: <span class="mark">6 бутылок (9 л.)</span>. Минимальный оптовый заказ: <span class="mark">5 упаковок</span></p>
        </blockquote>
        <figcaption class="blockquote-footer">Обьем 1.5</figcaption>
     </figure>
     <figure>
        <blockquote class="blockquote">
           <p>В одной упаковке: <span class="mark">1 КЕГ (50л)</span>. Минимальный оптовый заказ: <span class="mark">1 КЕГ</span></p>
        </blockquote>
        <figcaption class="blockquote-footer">Обьем 50</figcaption>
     </figure>
</div>
<hr>
{% endblock main_section %}

{% block other_section %}
{% endblock other_section %}

{% block new3_section %}
{% endblock new3_section %}

{% block footer  %}
{% endblock footer  %}